package service

var (
	kbCreateOrder          = "Создать заказ"
	kbActiveOrders         = "Активные заказы"
	kbItems                = "Позиции"
	kbAddItemPictogram     = "➕"
	kbRemovePictogram      = "➖"
	kbRemove               = "Удалить"
	kbEditItemPictogram    = "📝"
	kbQty                  = "Кол-во"
	kbPrice                = "Цена"
	kbName                 = "Имя"
	kbCustomer             = "Клиент"
	kbCustomerEmail        = "Эл. почта"
	kbCustomerInstagram    = "Instagram"
	kbCustomerPhone        = "Телефон"
	kbBack                 = "Назад"
	kbCancel               = "Отмена"
	kbPayment              = "Оплата"
	kbPaymentLink          = "Ссылка"
	kbPaymentCard          = "Перевод"
	kbPaymentCash          = "Наличные"
	kbFullPayment          = "Полная оплата"
	kbPartialPayment       = "Частичная оплата"
	kbFullRefund           = "Полный возврат"
	kbPartialRefund        = "Частичный возврат"
	kbRefundPayment        = "Возврат"
	kbOrderActions         = "Действия"
	kbOrderDone            = "Завершить заказ"
	kbOrderInProgress      = "В работу"
	kbOrderRestart         = "Возобновить заказ"
	kbOrderDelete          = "Удалить заказ"
	kbOrderRestore         = "Восстановить"
	kbOrderCollapse        = "Свернуть"
	kbOrderExpand          = "Развернуть"
	kbDelivery             = "Доставка"
	kbOk                   = "OK"
	kbLingerieSetPictogram = "👙"
	kbDeliveryPictogram    = "🚚"
)

var (
	kbDataItems           = "items"
	kbDataCustomer        = "customer"
	kbDataAddItem         = "order_add_item"
	kbDataRemoveItem      = "order_remove_item"
	kbDataEditItem        = "order_edit_item"
	kbDataBack            = "back"
	kbDataCancel          = "cancel"
	kbDataPayment         = "payment"
	kbDataPaymentLink     = "payment_link"
	kbDataPaymentCard     = "payment_card"
	kbDataPaymentCash     = "payment_cash"
	kbDataFullPayment     = "full_payment"
	kbDataPartialPayment  = "partial_payment"
	kbDataFullRefund      = "full_refund"
	kbDataPartialRefund   = "partial_refund"
	kbDataRemovePayment   = "order_remove_payment"
	kbDataRefundPayment   = "order_refund_payment"
	kbDataOrderActions    = "order_actions"
	kbDataOrderDone       = "order_done"
	kbDataOrderDelete     = "order_delete"
	kbDataOrderRestart    = "order_restart"
	kbDataOrderRestore    = "order_restore"
	kbDataOrderCollapse   = "order_collapse"
	kbDataOrderExpand     = "order_expand"
	kbDataOrderInProgress = "order_state_in_progress"
	kbDataDelivery        = "delivery"
	kbDataLingerieSet     = "lingerie"
	kbDataInstagram       = "instagram"
	kbDataNotifyRead      = "notify_readed"
)

var (
	replyMerchantSuccessfulRegistered = "Регистрация прошла успешно"
	replyWelcome                      = "Добро пожаловать!"
	replyEnterItemName                = "Введите наименование"
	replyEnterItemPrice               = "Введите стоимость"
	replyEnterItemQty                 = "Введите количество"
	replyEnterCustomerEmail           = "Введите адрес эл. почты"
	replyEnterCustomerInstagram       = "Введите имя пользователя"
	replyEnterCustomerPhone           = "Введите номер телефона"
	replyEnterAmount                  = "Введите сумму"
)
